### ISSUE TITLE
Add semicolons

### ISSUE THREAD

**Issue by patrick91** [ghzmdr/file-lister#1]
<3;

**Comment by marcoacierno** [comment]
+1

**Comment by vinzdef** [comment]
What if the world starts spinning the other way around, creating a parallel dimension.

In this dimension I would put semicolons and you won't.

The paradox we fall in is easily spotted: 
would I advise to put semicolons, or you to remove them?

BOOM!!! Fixed.

**Comment by patrick91** [comment]
I'd advice to be consistent with your team's coding style :)
